aeternity/testnet

channel_test.sh
docs/new_account.md
docs/todo.md
docs/using_channels.md
merging_experimental.md
src/bets/dice.fs
src/channels/channel_feeder.erl
src/channels/channel_manager.erl
src/consensus/constants.erl
src/consensus/txs/channel_solo_close.erl
src/consensus/txs/spk.erl
src/consensus/txs/test_txs.erl
src/dice.erl
src/easy.erl
src/free_constants.erl
src/networking/handler.erl
src/networking/internal_handler.erl
start.sh

this pull request adds ability to play satoshi dice.
This is a game like a slot machine.
you have 50% chance of losing your money, and a 50% chance of doubling it.
It uses statechannels, so it is trustless, and there are no transaction fees.

satoshi dice

---

docs/compile_mac.md

Necessary for initial app start on Mac.

Create necessary dirs for Mac setup

---

docs/commands_mining.md

Updated to match changed function in commit `b5c9aca963e8cf7aaa1d9419a92de7ccf4f0f776`

Update command in doc

---

docs/compile_linux.md
src/consensus/chain/block.erl
src/consensus/chain/block_absorber.erl
src/consensus/chain/block_hashes.erl
src/consensus/download_blocks.erl
src/free_constants.erl
src/networking/handler.erl

I changed the name of compile_ubuntu.md to compile_linux.md and reformatted it so one can add instruction how to install the dependencies on other distributions then arch. I also added the instructions for arch. The instructions for arch have been tested on docker base/archlinux image.
I introduced new request: `block_sizecap, First, Cap`. Where:
- First - the top block we would like to receive
- Cap - the max response size of response - blocks are added to response till it would make the response bigger then Cap
Using the new request I changed the trade blocks function to request blocks in bulk.

Compile on ArchLinux + Batch blocks download

---

Makefile
apps/ae_core/src/easy.erl
config/dev1/sys.config
config/dev2/sys.config
config/dev3/sys.config
config/local/sys.config
config/prod/sys.config
docs/mac_dependencies.md
temp.txt

adds install instructions for sed on mac. makes the sed commands compatible with mac.

now macs can connect to the network.

---

apps/ae_core/src/ae_core.app.src
apps/ae_core/src/ae_core_compile.erl
apps/ae_core/src/consensus/chain/block_absorber.erl
apps/ae_core/src/consensus/testnet_app.erl
apps/ae_core/src/gas_price.erl
config/sys.config.tmpl
rebar.config

Crashes with current version of MekleTrie - see dep repo for another PR

[depends on MerkleTrie PR] Use lagger for logging

---

docs/hiring.md

We are still looking for a blockchain wizard who dreams and thinks blockchain to support Zack. Get in touch!

Added some more hiring informations

---

Makefile
apps/ae_http/priv/swagger.json
apps/ae_http/src/ae_http_app.erl
apps/ae_http/src/ae_http_dispatch_ext.erl
apps/ae_http/src/ae_http_dispatch_int.erl
apps/ae_http/src/swagger/swagger_api.erl
apps/ae_http/src/swagger/swagger_header_handler.erl
apps/ae_http/src/swagger/swagger_router.erl
config/swagger.yaml
tests/test_swagger.py

Add GET /header/{blockId}

---

.travis.yml

Prevent spurious invocation of rebar in CI

---

.travis.yml

Please find example run at https://travis-ci.org/lucafavatella/testnet/builds/256826627#L734

In case of failure on CI, show logs in more structured way

---

apps/ae_api/src/api.erl
apps/ae_core/src/consensus/secrets.erl
apps/ae_http/priv/swagger.json
apps/ae_http/src/ae_http_dispatch_int.erl
apps/ae_http/src/swagger/swagger_api.erl
apps/ae_http/src/swagger/swagger_internal_handler.erl
apps/ae_http/src/swagger/swagger_router.erl
config/swagger.yaml
tests/swagger.py
tests/test_swagger_int.py

* secrets.erl cleanup
* Move test_new_lightning to acceptance tests

Implement POST /add-secret

---

apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/chain/headers.erl

Reformat, remove unused code. No functional changes.
@sennui

Reformat and remove unused code in block.erl and headers.erl

---

.travis.yml
ci

Please refer to commit messages for details.

Teach CI to run further checks

---

apps/.editorconfig

Please refer to commit message for details. See also https://github.com/aeternity/MerkleTrie/commit/2d4a6eae4d23fd3ce1dbf1b923022916fe111a2b
----
As some developers may perform some refactoring, I propose a structured approach for applying code conventions. These [can be improved](http://editorconfig.org/) of course e.g. `trim_trailing_whitespace`, `insert_final_newline`.

Plant partial specification of code style

---

apps/ae_http/priv/swagger.json
apps/ae_http/src/ae_http_dispatch_ext.erl
apps/ae_http/src/swagger/swagger_api.erl
config/swagger.yaml
tests/swagger.py

Extract fix from #244 . Thanks to @cytadela8 .
(Context is in https://github.com/aeternity/testnet/pull/244#issuecomment-319459468 and previous comments.)

#255 Fix mistake in Swagger spec re header

---

docs/design/blocks.md

#255 Draft description of block

---

ci

This is rebased version of PR #257. See https://github.com/aeternity/testnet/pull/257#issuecomment-319812007 for context.

Teach CI to check code generated from Swagger

---

apps/ae_core/src/ae_utils.erl
apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/chain/block_absorber.erl
apps/ae_core/src/consensus/chain/headers.erl
apps/ae_core/src/oracle_questions.erl

* Reorder fields in block and header records
* Refactor block_absorber.erl
* Extract binary_to_file_path to ae_utils
@sennui More 💅

Non-functional cleanup

---

apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/chain/headers.erl

More meaningful naming in header record

---

docs/getting-started/openSuSE_dependencies.md

initial doc to get Aeternity and Erlang on openSuSE Leap

getting started on openSuSE

---

docs/design/blocks.md

This PR follows conversations with @sennui and @zp-sd .

Detail description of block

---

apps/ae_core/src/consensus/trees/governance.erl

Governance.erl cleanup

---

apps/ae_core/src/consensus/chain/block.erl

#255 Delete code moved to `genesis_maker` function

---

apps/ae_core/src/consensus/chain/headers.erl

This change was developed while [improving the documentation](https://github.com/aeternity/testnet/pull/276) and attempting to reduce the distance between code and documentation for maintainability and readability.

Refactor block header serialization

---

.travis.yml
apps/ae_core/src/consensus/chain/headers.erl
apps/ae_core/src/consensus/tester.erl
apps/ae_core/src/consensus/trees/accounts.erl
apps/ae_core/src/consensus/txs/oracle_bet_tx.erl
apps/ae_core/src/consensus/txs/oracle_close_tx.erl
apps/ae_core/src/consensus/txs/oracle_new_tx.erl
apps/ae_core/src/consensus/txs/oracle_shares_tx.erl
apps/ae_core/src/consensus/txs/oracle_unmatched_tx.erl
ci

Teach CI to run tests in `tester`

---

docs/getting-started/erlang_install.md

As Emin mentioned this morning, I had a further look at the recently changed documents in the docs/ folder - hence this PR.

Delete redundant OTP installation instructions

---

.travis.yml

As Emin mentioned this morning, I had a further look at the recently changed documents in the docs/ folder - hence this PR.

Test OTP versions mentioned in docs/

---

apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/download_blocks.erl
apps/ae_core/src/consensus/trees/trees.erl
apps/ae_http/src/ext_handler.erl

Follows from https://github.com/aeternity/testnet/pull/279#pullrequestreview-54785605

Plant network serialization of block

---

docs/api/using_channels.md

(introduced by issue #291, PR #293)

Update API documentation reflecting the change of channel_balance

---

docs/design/lightning_speed_results.md
docs/design/trees.md
docs/getting-started/quick_start_developer_guide.md

Make recent blocks and accounts doc accessible, and polish some doc markup

---

apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/chain/headers.erl
apps/ae_core/src/consensus/trees/trees.erl
docs/design/blocks.md

Identify state trees included in block

---

apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/chain/block_absorber.erl
apps/ae_core/src/consensus/chain/block_hashes.erl
apps/ae_core/src/consensus/chain/headers.erl
apps/ae_core/src/consensus/tester.erl
apps/ae_core/src/consensus/tx_pool.erl
docs/design/blocks.md

Document node-local model of blocks

---

apps/ae_api/src/api.erl
apps/ae_core/src/consensus/trees/channels.erl
apps/ae_core/src/consensus/trees/oracles.erl
apps/ae_core/src/consensus/txs/channel_repo_tx.erl
apps/ae_core/src/consensus/txs/channel_team_close_tx.erl
apps/ae_core/src/consensus/txs/channel_timeout_tx.erl
apps/ae_core/src/consensus/txs/grow_channel_tx.erl
apps/ae_core/src/consensus/txs/new_channel_tx.erl
apps/ae_core/src/consensus/txs/spk.erl
docs/api/commands_channels.md
docs/design/blocks.md
docs/design/transaction_types.md
docs/design/trees.md

Depends on PR #324 (included in this PR).

Document key in channels state tree

---

.travis.yml

Relax CI checks until tests stable again

---

apps/ae_core/src/consensus/txs/txs.erl

Please refer to commit messages for details.
Refactoring performed while working on #255
(BTW It is likely I will need to open new PR re transactions that includes this PR.)

Refactor `txs` module

---

apps/ae_core/src/consensus/tx_pool_feeder.erl
apps/ae_core/src/consensus/txs/coinbase_tx.erl
apps/ae_core/src/consensus/txs/txs.erl

Depends on #329 (included in this PR).
I started work on transaction in order to identify potential relation with proofs - in scope of #255 .
I did not include signed transactions as the code gets tricky in doubly-signed transactions, but would get me out of scope for #255 .

Explicate structure of non-signed transaction

---

apps/ae_core/src/consensus/chain/block.erl
apps/ae_core/src/consensus/tx_pool.erl

Please refer to commit messages for details.
Refactoring performed while working on #255

Refactor `tx_pool` state computation

---

docs/design/chalang.md

This is #335 by @akorosmezey addressing [comments](https://github.com/aeternity/testnet/pull/335#pullrequestreview-57121429), GitHub markup, a few typos.

Move chalang-related docs into separate file

---

docs/todo.md

Delete coinbase todo item

---

docs/design/transaction_types.md

Depends on PR #339 (included in this PR) - in order to avoid merge conflict.

Review account-related transactions doc

---

rebar.config

Following CEO's request to remove deps

Remove chalang and trie deps (and all of their deps)
